### ISSUE TITLE
workflows/RSeQC/rseqc-bam-qc-SE.cwl: reference to non-existent step inputs

### ISSUE THREAD

**Issue by kaushik-work** [ncbi/cwl-ngs-workflows-cbb#30]
The tool `tools/basic/gzip.cwl` does not have inputs `c` and `outFileName`, however, steps in `workflows/RSeQC/rseqc-bam-qc-SE.cwl` refer to them as do steps in `workflows/File-formats/create-tagAlign.cwl`, `workflows/ChIP-Seq/gem.cwl` and `workflows/ChIP-Seq/peak-calling-MACS2.cwl`

Thanks!

**Comment by r78v10a07** [comment]
Hi,
Thank you so much for reporting this. I've fixed the problems.
See commit
