### ISSUE TITLE
Consider contributing the CWL tool descriptions to the community repo for shared maintenance

### ISSUE THREAD

**Issue by mr-c** [ncbi/cwl-ngs-workflows-cbb#74]
https://github.com/common-workflow-library/bio-cwl-tools

Thanks!

**Comment by r78v10a07** [comment]
Hi @mr-c ,
Thanks for inviting me to contribute with the community. I will be glad to do that.
Unfortunately, do to project requirements we need to keep this repositories as it is used for many other applications.
You can, of course, take any CWL from this repo and add it to the community one. 
Our license is Public Domain.
Thanks,
Roberto
